### ISSUE TITLE
TextDocumentDidSave with optional string `text' crashes the server

### ISSUE THREAD

**Issue by wkirschbaum** [elixir-tools/next-ls#105]
For TextDocumentDidSave, the server will crash when the text property is nil, which can be nil according to the spec: https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_didSave.

Potential fix: 

```diff
@@ -337,7 +337,7 @@ defmodule NextLS do
 
     {:noreply,
      lsp
-     |> then(&put_in(&1.assigns.documents[uri], String.split(text, "\n")))
+     |> then(&put_in(&1.assigns.documents[uri], String.split(text || "", "\n")))
      |> then(&put_in(&1.assigns.refresh_refs[task.ref], {token, "Compiled!"}))}
   end
```

**Comment by mhanberg** [comment]
technically this is incorrect behavior by the editor, as they are supposed to send the text when the server capabilities specify it

https://github.com/elixir-tools/next-ls/blob/main/lib/next_ls.ex#L102

It's unclear to me what the ramifications are, in that if we don't have the text, we can't compute document symbols (i mean we could technically, but we're not really supposed to read from the filesystem)

**Comment by wkirschbaum** [comment]
The spec does say text can be null, so assuming it is when nothing changes.

**Comment by mhanberg** [comment]
From the spec

```
/**
	 * Optional the content when saved. Depends on the includeText value
	 * when the save notification was requested.
	 */
```

I think this supports what I previously said

**Comment by mhanberg** [comment]
Where is the actual eglot source code? it looks like lsp-mode should do this correctly, but for eglot i found this https://github.com/joaotavora/eglot/blob/master/eglot.el#L2653C1-L2663C56 (which implies it sends it regardless of what the server says), but i don't think that is the up to date eglot code

**Comment by wkirschbaum** [comment]
I have not testes on eglot yet, this was for lsp-mode.

**Comment by wkirschbaum** [comment]
Ah, if include text is true, then it must be a bug on lsp-mode, will have a look.

**Comment by mhanberg** [comment]
https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L5008-L5015

**Comment by wkirschbaum** [comment]
Yes, but `(lsp--save-include-text-p)` returns nil, so something is wrong.

**Comment by wkirschbaum** [comment]
lsp-mode will only respect the save registration options when considering if it should send the text, but from my basic understanding it that it should consider both the save options and the save registration options. 

I don't really understand how registration works, but does not seem to be supported by next-ls.
