### ISSUE TITLE
Is formatting compatible with "mix format"?

### ISSUE THREAD

**Issue by thbar** [elixir-tools/next-ls#114]
When working with `vscode-elixir-ls` and the `editor.formatOnSave = true` option, quite often you'll end up with format-only changes that are different from the ones brought by `mix format`. This makes it a bit painful to work with `vscode-elixir-ls` in that regard (you either re-run `mix format`, or hand-pick the right changes when committing with git etc).

See: https://github.com/elixir-lsp/vscode-elixir-ls/discussions/224

With `next-ls`, will this problem remain the same? It would be a great improvement if the formatting was directly compatible with `mix format`.

**Comment by mhanberg** [comment]
It should produce the same result as running `mix format` and respect your .formatter.exs

But i'll say that I think elixir-ls should do the same if you upgrade your project to elixir v1.15, there was a recent improvement in Elixir that made that more reliable
