### ISSUE TITLE
NextLS crashes when the project deps updates

### ISSUE THREAD

**Issue by wkirschbaum** [elixir-tools/next-ls#115]
After running `mix deps.update --all` on a project using NextLS, the NextLS server crashes with the following error: 

```bash
[NextLS] NextLS v0.5.4 has initialized!
[NextLS] Booting runtime...
[NextLS] Unchecked dependencies for environment dev:
[NextLS] * flop (Hex package)
[NextLS]   the dependency does not match the requirement "~> 0.22.0", got "0.21.0"
* flop_phoenix (Hex package)
[NextLS]   the dependency does not match the requirement "~> 0.21.0", got "0.19.1"
[NextLS] ** (Mix) Can't continue due to errors on dependencies
[NextLS] The runtime has crashed
```

After deleting and the .elixir-tools directory it recompiles and works again.

**Comment by mhanberg** [comment]
Did you modify mix.exs first?

**Comment by wkirschbaum** [comment]
Only mix.lock changed.

**Comment by mhanberg** [comment]
Sorry, I mean did you run mix deps.update while Next LS was already running?

**Comment by mhanberg** [comment]
Interesting, I would not have expected the need to delete the .elixir-tools folder

**Comment by mhanberg** [comment]
Related #53

**Comment by mhanberg** [comment]
I believe https://github.com/elixir-tools/next-ls/pull/401 should close out this issue, I will likely release it in v0.20.2, please update and let me know if you can still reproduce.

I'll close the issue if I don't hear back in a while, but feel free to comment and I'll re-open
