### ISSUE TITLE
How does formatting work in VSCode?

### ISSUE THREAD

**Issue by cvkmohan** [elixir-tools/next-ls#123]
I have installed https://github.com/elixir-tools/elixir-tools.vscode and enabled nextLS.  
However, when I try to format the document, VSCode says no formatter installed. How do I get started with this?
Sorry, if the question is too trivial.

**Comment by mhanberg** [comment]
Can you try restarting vscode. 

It should just work.

**Comment by cvkmohan** [comment]
```
[Trace - 10:17:32 PM] Sending request 'initialize - (0)'.
[Error - 10:17:33 PM] Client NextLS: connection to server is erroring. Shutting down server.
[Error - 10:17:33 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at _.shutdown (/home/krishna/.vscode-server/extensions/elixir-tools.elixir-tools-0.3.1/dist/extension.js:2:96701)
	at _.stop (/home/krishna/.vscode-server/extensions/elixir-tools.elixir-tools-0.3.1/dist/extension.js:2:96282)
	at _.stop (/home/krishna/.vscode-server/extensions/elixir-tools.elixir-tools-0.3.1/dist/extension.js:2:258296)
	at _.handleConnectionError (/home/krishna/.vscode-server/extensions/elixir-tools.elixir-tools-0.3.1/dist/extension.js:2:102789)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This is the error log that vscode is showing.
I am running elixir 1.15.4 on erlang 26.0.2

**Comment by mhanberg** [comment]
Are you using WSL?

**Comment by cvkmohan** [comment]
Yes. Is it a known issue?

**Comment by mhanberg** [comment]
https://github.com/elixir-tools/next-ls/issues/102

**Comment by cvkmohan** [comment]
Sorry for bothering you again. 
The same setup - is not generating any error - when Credo Language Server is started. ( I disabled NextLS start.) 
However, formatting etc. are not working.

The question is - AutoFormat, Code Suggestions etc. are specific to NextLS only? It seems only NextLS is getting that startup error in WSL.

**Comment by mhanberg** [comment]
Formatting is a next ls feature, not a credo language server feature. (They are two different projects.)

I'm not sure what you mean by code suggestions exactly. Credo language server has a couple code actions (the lightbulb suggestions). 

I don't have a windows computer so I'll need to get a VM booted to debug the WSL stuff. (Assuming a windows user doesn't get to it first)

**Comment by cvkmohan** [comment]
Thanks for the response. 
No - my intention is not to hurry you on a solution in this. 
I just wanted to highlight the fact that the wsl error is only for NextLS. Just maybe, it might trigger something. :)
I will try to debug a bit more - and - report to you - if there is anything specific.

Thanks for all the effort.

**Comment by mhanberg** [comment]
Thanks! I appreciate it.
