### ISSUE TITLE
NextLS crashes when booting

### ISSUE THREAD

**Issue by crbelaus** [elixir-tools/next-ls#146]
I am getting the following error when the NextLS server tries to initialize:

```
** (Mix.Error) Hex dependency resolution failed
    (mix 1.15.2) lib/mix.ex:577: Mix.raise/2
    (mix 1.15.2) lib/mix/dep/converger.ex:141: Mix.Dep.Converger.all/4
    (mix 1.15.2) lib/mix/dep/converger.ex:74: Mix.Dep.Converger.converge/4
    (mix 1.15.2) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix 1.15.2) lib/mix/tasks/deps.get.ex:34: Mix.Tasks.Deps.Get.run/1
    (mix 1.15.2) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.2) lib/mix.ex:874: anonymous fn/5 in Mix.install/2
    (elixir 1.15.2) lib/file.ex:1624: File.cd!/2
[Error - 09:14:20] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 09:14:20] The NextLS server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 09:14:20] NextLS client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 09:14:20] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
```

I am having this exact same error in two different computers and both in my day job and in the NextLS repository.

**Comment by crbelaus** [comment]
I completely removed the elixir-tools extension folder in VSCode and reinstalled it from scratch but the error persists.

**Comment by treshenry** [comment]
Just adding a +1. Linux, nvim, elixir-tools.nvim 0.7.2.

![image](https://github.com/elixir-tools/next-ls/assets/35269/14c15eaf-3ef7-4815-80be-93b112025b1a)

From `lsp.log`

```
[ERROR][2023-08-09 11:44:02] .../vim/lsp/rpc.lua:734    "rpc"   "/home/tres/.local/share/nvim/lazy/elixir-tools.nvim/lua/elixir/../../bin/nextls"       "stderr"     "** (Mix.Error) Hex dependency resolution failed
    (mix 1.15.4) lib/mix.ex:577: Mix.raise/2
    (mix 1.15.4) lib/mix/dep/converger.ex:141: Mix.Dep.Converger.all/4
    (mix 1.15.4) lib/mix/dep/converger.ex:74: Mix.Dep.Converger.converge/4
    (mix 1.15.4) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix 1.15.4) lib/mix/tasks/deps.get.ex:34: Mix.Tasks.Deps.Get.run/1
    (mix 1.15.4) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.4) lib/mix.ex:881: anonymous fn/5 in Mix.install/2
    (elixir 1.15.4) lib/file.ex:1624: File.cd!/2"
```

**Comment by mhanberg** [comment]
So yesterday, mix install basically stopped working and I think this is related, but the condition has worsened. 

In 0.8 I am now distributing pre built binaries, I am just still getting the editor extensions updated. 

I have a PR open in the neovim plug-in and will be tackling the vscode extension today.

**Comment by mhanberg** [comment]
Oh, this is not related to it not working. 

This is because I have made the 0.8 GitHub release but haven't published it to hex pm, because I'm not going to do that anymore.

**Comment by mhanberg** [comment]
@treshenry if you update elixir-tools.nvim to v0.8.0, it should work again. it will prompt you to install nextls and download a pre-built binary from the github release

@crbelaus i'm still working on updating the vscode plugin

**Comment by mhanberg** [comment]
Going to close this as it is fixed in NextLS, but i'll open another issue in the vscode plugin

**Comment by treshenry** [comment]
Woot! Just updated elixir-tools.nvim to 0.8.1 (auto-pulled by Lazy) and got a small install prompt. Everything looks great so far! No crashes and a basic kick-the-tires seems good. Gold star for you! ⭐
