### ISSUE TITLE
[NextLS] sqlite3 error: NOT NULL constraint failed: references.start_line

### ISSUE THREAD

**Issue by ndan** [elixir-tools/next-ls#160]
I've installed elixir-tools.vscode from the marketplace, and it's working, but there are tons of errors in the NextLS output.

```
statement: INSERT INTO 'references' (identifier, arity, file, type, module, start_line, start_column, end_line, end_column)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
[Error - 10:12:27 AM] [NextLS] sqlite3 error: NOT NULL constraint failed: references.start_line
```

elixir-tools: 0.6.0
elixir: 1.15.4-otp-26
erlang: 26.0.2
OS: MacOS Ventura (13.4.1)
VSCode: 1.81.0

**Comment by mhanberg** [comment]
Thanks for the detailed report!

I've noticed these as well, it shouldn't effect anything really, unless you notice poor results in the Find References feature. 

It should probably say warn instead of error. 

Let me know if you see any inaccuracies there.

**Comment by mhanberg** [comment]
I should clarify that these are alarming and I will look into them, but the presence of them means the LSP should still be functional rather than broken.

**Comment by mhanberg** [comment]
I think for these, these are functions that are generated by elixir and don't have a spot in the source code, so we coalesce the nil line into `1` (or 0, whatever it is supposed to be)
