### ISSUE TITLE
Next LS not compatible on Ubuntu 20.XX or systems with older glibc versions than 2.34

### ISSUE THREAD

**Issue by polvalente** [elixir-tools/next-ls#189]
As discussed in Discord, this is probably due to OS/glibc version combo.
Currently running elixir-tools 0.6 for vscode, OS is Ubuntu 20.04.6 (x86_64) and glibc is 2.31-0ubuntu9.9

**Comment by tanguykurylo** [comment]
The universal-linux binary works on Ubuntu 20.04.6 LTS x86_64 with glibc 2.31-0ubuntu9.14 and elixir-tools 0.12.1
(Thank you so much @doawoo)

**Comment by mhanberg** [comment]
This should be fixed as of v0.17.0, thanks to updating to Burrito v1.0 and lots of support from @doawoo.
