### ISSUE TITLE
Ignoring line_length?

### ISSUE THREAD

**Issue by stevencorona** [elixir-tools/next-ls#216]
Hi!

Love the project. I'm running in VSCode - I believe the latest version of NextLS. I am working in an umbrella app with `line_length: 120` set in `.formatter.exs`. Formatting is working well, but it seems to be ignoring the custom line length. Is this a known/expected issue?

```
Library/Application Support/.burrito 
➜ ls -lah
total 0
drwxr-xr-x   3 steve  staff    96B Sep 13 09:00 .
drwx------+ 90 steve  staff   2.8K Sep 13 08:58 ..
drwxr-xr-x   7 steve  staff   224B Sep 13 09:00 next_ls_erts-14.0.2_0.11.0
```

**Comment by mhanberg** [comment]
No, it should respect it.

Can you provide an example file that reproduces the issue (meaning, running `mix format` does not produce the same result as formatting via the LSP).

> Love the project. 

Thank you, very appreciated 🤗

**Comment by mhanberg** [comment]
@stevencorona friendly bump

**Comment by stevencorona** [comment]
It randomly started working again - hah. Not sure what changed. I restarted VSCode and killed the beam process several times with success.

Have been using it the past few days on a pretty large elixir codebase (150k lines) and it's been seemingly working reliably.

Excited to see the project develop, will look for some ways to contribute.

**Comment by mhanberg** [comment]
hmm, weird haha. no worries!

> Excited to see the project develop, will look for some ways to contribute.

thanks! reporting issues and using it while it's pre-1.0 is very helpful on it's own, but feel free to take a look at the issues and hack away on any of them!
