### ISSUE TITLE
Setup next-ls with lspconfig in neovim

### ISSUE THREAD

**Issue by andres-river** [elixir-tools/next-ls#233]
Hello there, I really want to try next-ls but I'm wondering if there are any guides or even rough instructions on how to set it up with lspconfig. I tried changing the command to execute, but running `nextls --port 9000` doesn't seem to work.

I'm want to avoid installing elixir-tools.nvim as I will need to setup everything again.

Thank you.

**Comment by mhanberg** [comment]
Hi!

I don't have instructions off hand, but I'm interesting in knowing what you mean by "I'm want to avoid installing elixir-tools.nvim as I will need to setup everything again."

Installing elixir-tools.nvim shouldn't require you to change any of your other configuration.

**Comment by andres-river** [comment]
So I have lspconfig setup with specific keybinds that I can use across languages. If I was to setup elixir-tools.nvim, I assume these keybinds will need to be setup somehow? And there might be collisions with `lspconfig`.

**Comment by mhanberg** [comment]
You can pass the same callback you pass to lspconfig to elixir tools. 

Here is a section of the README that shows the on_attach callback you can use. 

But if you put your keybinds in an LspAttach callback (that's what I recommend) then it should just work.

**Comment by mhanberg** [comment]
```lua

elixir.setup {
  nextls = {
    enable = false, -- defaults to false
    port = 9000, -- connect via TCP with the given port. mutually exclusive with `cmd`. defaults to nil
    cmd = "path/to/next-ls", -- path to the executable. mutually exclusive with `port`
    on_attach = function(client, bufnr)
      -- custom keybinds
    end
  },
}

```

**Comment by mhanberg** [comment]
Elixir tools nvim will properly handle umbrella apps and workspaces, which lspconfig will not

**Comment by mhanberg** [comment]
Going to close this, as it's not an issue
