### ISSUE TITLE
Can't hover on well known functions

### ISSUE THREAD

**Issue by andrepaes** [elixir-tools/next-ls#241]
Hey, i'm trying to hover on functions that i'm pretty sure that has docs and the lsp is saying that it doesn't exists. For some functions it works but for others don't, so i think it's not related with my nvim configs.
![image](https://github.com/elixir-tools/next-ls/assets/12038420/49b6702a-0793-4fb7-9c48-a8b64dfe9e98)
Some functions on Map module works but others don't, the same occurs for Enum module and for custom functions/types.
![image](https://github.com/elixir-tools/next-ls/assets/12038420/65c96293-23b2-402c-94f6-0b7ea3c6c294)
![image](https://github.com/elixir-tools/next-ls/assets/12038420/28be9e78-ffdf-4fd7-9080-18c0d1833947)

Thanks in advance,
André Luiz

**Comment by mhanberg** [comment]
Thanks for the report

I think the first thing is because we might not being indexing types yet.

The third screenshot seems to be odd.

would you mind copy pasting that code so i can test it?

also as a quick test, can you see what happens if you format that last snippet like this and hten save and check

```elixir
expected_payload = Map.take(
  body,
  Map.keys(@bet_payload_keys)
)
```

if that is the case, it might be related to #184

**Comment by andrepaes** [comment]
It seems to not be related with the format.
![image](https://github.com/elixir-tools/next-ls/assets/12038420/22286397-52f2-4ac1-a73e-439af7d93b24)

`
defmodule Parsers.Bet do
  @bet_payload_keys %{
    user: &is_binary/1,
    transaction_uuid: &is_binary/1,
    round: &is_binary/1,
    request_uuid: &is_binary/1,
    game_code: &is_binary/1,
    currency: &is_binary/1,
    bet: &is_binary/1,
    amount: &is_integer/1
  }

  @spec parse(map()) :: {:ok, map()} | {:error, :wrong_types}
  def parse(body) do
    expected_payload =
      Map.take(
        body,
        Map.keys(@bet_payload_keys)
      )

    valid_types? =
      Enum.all?(expected_payload, fn {key, value} ->
        validator = @bet_payload_keys[key]

        validator.(value)
      end)

    if valid_types? do
      {:ok, expected_payload}
    else
      {:error, :wrong_types}
    end
  end
end

`
