### ISSUE TITLE
Formatter fails on Elixir 1.12.3

### ISSUE THREAD

**Issue by sb8244** [elixir-tools/next-ls#274]
I need to upgrade this app—I understand not supporting this older version.

It would be useful for next-ls to yell at me that I have the wrong version.

**Comment by mhanberg** [comment]
I believe https://github.com/elixir-tools/next-ls/pull/401 should close out this issue, I will likely release it in v0.20.2, please update and let me know if you can still reproduce.

I'll close the issue if I don't hear back in a while, but feel free to comment and I'll re-open
