### ISSUE TITLE
No case clause for "attribute" with VSCode 1.82.3

### ISSUE THREAD

**Issue by fhunleth** [elixir-tools/next-ls#280]
I'm not quite sure how to reproduce this, but it just started recently. Everything works fine with VSCode and then at some point I get the following error repeatedly and VSCode stops letting me save the file that I'm working on.

```
** (CaseClauseError) no case clause matching: "attribute"
    (next_ls 0.13.4) lib/next_ls.ex:337: NextLS.handle_request/2
    (gen_lsp 0.6.0) lib/gen_lsp.ex:248: anonymous fn/5 in GenLSP.loop/3
    (gen_lsp 0.6.0) lib/gen_lsp.ex:308: GenLSP.attempt/3
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

It seems like one easy fix would be to ignore unknown reference types. I didn't know whether that was a bad idea so I figured that I'd post the issue.

**Comment by mhanberg** [comment]
Yes, it should just return nil in that case.
