### ISSUE TITLE
Configure Credo Extension

### ISSUE THREAD

**Issue by mhanberg** [elixir-tools/next-ls#288]
## Description

For giant projects, Credo can take a _long_ time. 

For those projects, it would be beneficial to be able to change exactly how credo is run on that project.

I think there are three potential settings

- Enabled
    - Control whether the extension runs at all (defaults to true)

- Single File vs Whole Project
    -  This setting would control as to whether credo is only ran on the file that was just saved, or the whole project. (defaults to whole project)

- CLI options
    - Credo is programmatically still controlled via it's CLI options, and currently it's run with `["--strict", "--all", "--working-dir", dir]`, with `dir` being the root of the project.

**Comment by tensiondriven** [comment]
I'll second this; currently, my project uses Credo on CI without `--strict`, but I can't ask elixir-tools or credo language server to do anything other than `--strict --all`, so my Problems pane is flooded with issues that aren't relevant.

I've tried deleting `.credo.exs`, but it looks like elixir-tools still picks up that Credo is installed based on Credo being present in mix.exs (?).  

I tried setting up an alternate config (other than "default", but I don't see any way to specify the config to use.

I will try adding .credo.exs to my .gitignore and changing the "default" config to omit all checks for now.

(On a personal note, I really hope I can get this working; there's no way I'm going back to ElixirLS if I can help it!)

**Comment by mhanberg** [comment]
It detects credo by detecting if `Credo` is loaded in the project runtime (the beam VM that is started for you project).

rather than configuring the CLI options, it might be better to make sure that it just respects your .credo.exs instead (which i think it would do I removed the CLI options used in the extension code)

**Comment by atonse** [comment]
Thanks for your work on this. I just installed this extension and am quite excited to see its improvements over ElixirLS.

We only run credo in our project with `--min-priority high` – is there a way to configure the minimum priority at the extension level? I didn't see it in the docs.

**Comment by tensiondriven** [comment]
@atonse Its such a step up from ElixirLS, isn't it? (Ok, that's all i came to say)

**Comment by mhanberg** [comment]
> Thanks for your work on this. I just installed this extension and am quite excited to see its improvements over ElixirLS.
> 
> We only run credo in our project with `--min-priority high` – is there a way to configure the minimum priority at the extension level? I didn't see it in the docs.

Not yet, that is what this ticket is tracking. I might be able to knock this out tonight or later this week! (but, anyone else is free to tackle it as well, it should be straight forward to add another initialization option for credo and to pass it to the credo extension)

**Comment by atonse** [comment]
thanks for the quick response @mhanberg – will try to look at this in a week if you haven't, but a bit swamped under deadline (still not swamped enough to have tried the extension though)

@tensiondriven Don't know yet haha – right now I'm mortified at the number of warnings about our code! But it is already quite nice and I'm hoping to just somehow trick my mind to ignore all the credo red errors to keep working with it. 

I wish that `mix format` could just auto-correct some of these silly (but nice to have) credo issues, like changing the ordering of aliases.

**Comment by mhanberg** [comment]
@atonse actually, quick question, do you have that min-priority flag in your .credo.exs config? or do you use it on the command line?

> I wish that mix format could just auto-correct some of these silly (but nice to have) credo issues, like changing the ordering of aliases.

You might take a look at [Styler](https://github.com/adobe/elixir-styler/). I actually use it on the Next LS codebase. It basically has fixers for a subset of Credo rules, which allows you to automatically fix them, as well as turn off those rules in your credo config so it doesn't even spend time checking them.

**Comment by atonse** [comment]
@mhanberg 

Thank you! I'll try adding styler.

I actually checked our `credo.exs` first based on this thread before asking (because I agree that most of this config should just go in there and perhaps then the config for next-ls is "which credo named config to use?") but I didn't see anything.

You can define the priority for each rule, but I didn't see anything like a "minimum priority"

**Comment by mhanberg** [comment]
I will be putting up PRs for this ticket later today!

**Comment by atonse** [comment]
@mhanberg thanks for getting this done so quickly. I like your solution which is very open-ended (allowing us to put in anything for the cli options).

Do you know when the VS code extension update will hit the VS code store? I'd love to try this out. I had to stop using elixir-tools because a lot of the credo issues were highlighting in our files as red (errors) and making the app look completely broken.

**Comment by mhanberg** [comment]
When I merge #323, it enter the release pipeline and a new github release will be published and binaries uploaded to it.

At that point, your local Next LS binary will auto update the next time it is booted up, but I stil need to make a patch and cut a release to the elixir-tools.vscode so that the settings are surfaced in the VSCode UI

**Comment by mhanberg** [comment]
I was going to wait until I had added some docs to the website, but I can release it sooner so you can test it out

**Comment by atonse** [comment]
No rush at all @mhanberg, you're already releasing this stuff quickly enough. I'll just continue to keep an eye.

**Comment by mhanberg** [comment]
also all repos have an rss feed for releases that you can subscribe to if you use rss
