### ISSUE TITLE
Incorrect Project Diagnostics: module not loaded and could not be found

### ISSUE THREAD

**Issue by kevinschweikert** [elixir-tools/next-ls#297]
Hey,

i am using NextLS with Zed and used [Petal Components](https://petal.build/components#install_petal_components) in my project. The project compiles and works fine but the LSP shows me some errors like:  `module PetalComponents is not loaded and could not be found. This may be happening because the module you are trying to load directly or indirectly depends on the current module`

For Petal Components you have to add this to `myapp_web.ex`

```elixir
defp html_helpers do
    quote do
     ....
      use PetalComponents
    ....
    end
  end
```

and i use them in my files like `use MyAppWeb, :html` or `use MyAppWeb, :live_view`.
The using macro is defined [here](https://github.com/petalframework/petal_components/blob/main/lib/petal_components.ex).

Does this help? Do you need more information?

**Comment by mhanberg** [comment]
Could you try quickly to delete the .elixir-tools directory and then reopen zed?

If that doesn't work, please share your projects versions of elixir, OTP, etc

**Comment by kevinschweikert** [comment]
I already tried deleting the directory but without closing zed. I tried it again with "close zed", "delete directory", "restart zed" and now it works. sorry for the trouble!

Elixir: 1.15.6
OTP: 26.1

**Comment by mhanberg** [comment]
Thanks for double checking!

These transient errors are something I'm hoping to squash, so every issue like this is very helpful!
