### ISSUE TITLE
No feedback if the Mix project can't compile

### ISSUE THREAD

**Issue by whatyouhide** [elixir-tools/next-ls#301]
To reproduce this, I just installed the VS Code extension and entered "Yes" when prompted to install  NextLS.

I have NextLS installed:

```
→ ls -la ~/.cache/elixir-tools/nextls/bin 
.rwxr-xr-x@ 6.5Mi andrea.leopardi staff 25 Oct 09:51 nextls*
```

Then, I hopped into an Elixir project and formatting didn't work. No feedback from NextLS/elixir-tools.vscode, just didn't work. If I tried to manually format the file (<kbd>⌥</kbd>+<kbd>⇧</kbd>+<kbd>f</kbd>), VS Code yelled at me for having no formatters for Elixir installed.

So, I traced the output of elixir-tools.vscode and found this out:

<details>
 <summary>Trace output</summary>

```
[NextLS] Beginning DB migration...
[Info  - 10:00:43] [NextLS] Database is on the latest version: 5
[NextLS] Finished DB migration...
[NextLS] Using `elixir` found at: /Users/andrea.leopardi/.asdf/shims/elixir
[NextLS] Unchecked dependencies for environment dev:
* dialyxir (Hex package)
[NextLS]   lock mismatch: the dependency is out of date. To fetch locked version run "mix deps.get"
[NextLS] ** (Mix) Can't continue due to errors on dependencies
[Error - 10:00:43] [NextLS] Runtime for folder redix failed to initialize
[Error - 10:00:43] [NextLS] The runtime for redix has crashed with reason: {:shutdown, :portdown}
```

</details>

Turns out it was a simple problem of not having run `mix deps.get` on the project yet. Once I ran `mix deps.get` manually, everything started to work.

## Approaches

  * elixir-tools.vscode should probably bubble up errors somehow, otherwise users just don't know that it's not working?
  * Maybe running `mix deps.get` should be done by elixir-tools.vscode, even though it potentially changes `mix.lock`, so not sure this is a good idea.
  * Formatting doesn't need `mix deps.get` to run *unless there are dependencies in `:import_deps` in `.formatter.exs`*. Just throwing this out there.

⚠️ Disclaimer: I come from a place of users. No clue on VS Code extensions or anything like that, I’m just a VS Code user and I care about Elixir obviously 😄 

Thanks for all the great work!

**Comment by mhanberg** [comment]
> Thanks for all the great work!

I really appreciate it! Thanks for being an early adopter and trying it out!

Note: I transferred this ticket to the next-ls repository, as it's not really an elixir-tools.vscode issue

> elixir-tools.vscode` should probably bubble up errors somehow, otherwise users just don't know that it's not working?

The trick would be knowing which errors should be presented to the user and which ones are normal, like the app not compiling because you have a syntax error. Probably doable tho!


> Maybe running mix deps.get should be done by elixir-tools.vscode, even though it potentially changes mix.lock, so not sure this is a good idea.

See #53 

> Formatting doesn't need mix deps.get to run unless there are dependencies in :import_deps in .formatter.exs. Just throwing this out there.

It's unclear to me what the exact reason here for the formatting not functioning, so I'll have to take a closer look. But my suspicion is that since the very first compilation request failed, the runtime shutdown and then the server is more or less inert until it's rebooted.

---

Thank you for the very detailed bug report!

**Comment by whatyouhide** [comment]
Closing this as I’m doing cleanup of my open issues. I’m not using NextLS now so I wouldn't be able to help with debugging either. Thanks peeps! 💟
