### ISSUE TITLE
next-ls not respecting project and deps  .formatter.exs

### ISSUE THREAD

**Issue by tensiondriven** [elixir-tools/next-ls#302]
When I open a schema file and save, `field` statements get local parens applied, however ecto's `.formatter.exs` specifies `locals_without_parens` which should prevent next-ls from adding these parens.

Am i missing a step in my configuration?  Can I provide any additional debug info?

**Comment by tensiondriven** [comment]
It looks like my issue was due to an error in another file.  That syntax error was causing next-ls to fail, and then on save, the file was being formatted without the help from `.formatter.exs`.  Perhaps this can be closed; however it's still kind of a bummer that a syntax error in another file can cause `.formatter.exs` to be ignored.  Is that possible?

**Comment by mhanberg** [comment]
did the other file have a syntax error when you started up the editor? meaning, did the syntax editor exist before the LSP was initializing?

I think this issue might be similar to #301

**Comment by tensiondriven** [comment]
I'm not sure, I think that's a reasonable assessment though.  I'll close for now in favor of #301 and keep an eye out for future cases.  @mhanberg if you disagree, please don't hesitate to reopen!  Thanks again for improving the lives of Elixir devs everywhere.
