### ISSUE TITLE
compile: error in parse transform

### ISSUE THREAD

**Issue by mrluc** [elixir-tools/next-ls#303]
Figured I'd give Zed a whirl! Experience report -- without doing anything, it highlighted Elixir code nicely, and I love how snappy it is.

However, with latest Zed 0.108.2, adding the next-ls snippet and restarting ...
```
"elixir": {
    "lsp": "next_ls"
}
```

Gives me this when opening an Elixir project:
```
%% -*- erlang-indent-level: 4;indent-tabs-mode: nil -*-
exception error: undefined function parse_trans:initial_context/2  in function  
parse_trans_codegen:parse_transform/2 (src/parse_trans_codegen.erl, line 147)  
in call from compile:foldl_transform/3 (compile.erl, line 1195)  in call from 
compile:fold_comp/4 (compile.erl, line 410)  in call from 
compile:internal_comp/5 (compile.erl, line 394)  in call from 
compile:'-internal_fun/2-anonymous-0-'/2 (compile.erl, line 227)  
in call from compile:'-do_compile/2-anonymous-0-'/1 (compile.erl, line 217)
%% --------------------------------------------------
```
<img width="554" alt="image" src="https://github.com/elixir-tools/next-ls/assets/38204/f6cfe2bd-196b-489f-add8-1e4324c4cc3f">

Could that be due to an old system version of elixir or something? I usually use `.tool-versions` to manage those, and this project has a .tool-versions, but I can imagine that maybe Zed / this LS might not use them.

**Comment by mhanberg** [comment]
I think zed might have an issue where it is not propagating the environment to the LSP when they start it, so then when Next LS goes to start a runtime for your project, it doesn't find the correct Elixir and OTP.

@mikayla-maki could you maybe look into that if you have a chance? I think we have briefly talked about this before.

**Comment by mhanberg** [comment]
Cleaning up issues, I think this is probably a zed problem
