### ISSUE TITLE
Configure project root?

### ISSUE THREAD

**Issue by cigrainger** [elixir-tools/next-ls#328]
In elixir-ls, you can set `elixirLS.projectDir`. I have a monorepo with multiple Elixir projects I'd love to open in Zed. In nvim it's no problem because the mix file is detected as the nearest project root. But Zed/VSCode don't play nicely with that. Any tips? Thanks!

**Comment by mhanberg** [comment]
For monorepos, you'll want to use workspace folders. 

In VSCode, here is a video showing how to do it: https://www.elixir-tools.dev/next-ls/#workspace-folders

For Zed, unfortunately they don't support workspace folders yet (I am pretty sure at least, I will double check). So the only work around is to open the specific sub folder you want to work in.

**Comment by mhanberg** [comment]
Just to confirm, the `elixirSL.projectDir` setting would only help you use one project at a time, correct?

**Comment by mhanberg** [comment]
In Neovim, the support isn't as good, but it is still possible. there is API to do `:lua vim.lsp.buf.add_workspace_folder("app1")`

There is an easy change I can make to elixir-tools.nvim (it would still take some config on your side tho) to make it rather painless.

But yes, in VSCode, you just need to add all of your project folders to your workspace.

you can easily do it via the CLI with `code -a app1 -a app2 -a app3 .` (i think thats the syntax, might take some fiddling.

let me know if the neovim thing is interesting to you and i can prioritize it!

**Comment by mhanberg** [comment]
I am going to close this tho as its not really an issue

**Comment by cigrainger** [comment]
> I am going to close this tho as its not really an issue

All good, thanks for the help <3

> let me know if the neovim thing is interesting to you and i can prioritize it!

Definitely is, that's where I spend most of my time!

**Comment by dvcrn** [comment]
Old issue, but ran into this issue switching from ElixirLS to NextLS. What's the go to way here to setup a project root when not using vscode? 

Getting the usual

```
[Next LS] Runtime for folder  is ready...
[Next LS] Unexpected compiler response: {:error, %{message: "Could not find a Mix.Project, please ensure you are running Mix in a directory with a mix.exs file", __struct__: Mix.NoProjectError, __exception__: true, mix: true}}
```

In ElixirLS this was an easy fix with `projectDir`. 

I can of course open the sub folder as a separate workspace which would make it work, but then I lose the ability to reference files across the entire project, eg working on frontend (not in Elixir) and backend (Elixor) at the same time

**Comment by mhanberg** [comment]
Ahh, sorry I misunderstood that part.

Other editors can support workspace folders, its a feature of LSP. What editor are you using?

**Comment by dvcrn** [comment]
I'm using Zed, but I think the main issue is the same across editors, the elixir project root isn't always in the project roof of the repository. It's not always feasible to launch multiple windows for each section (eg frontend/backend), so the `projectDir` setting of ElixirLS was quite nice 

I think Zed does have workspace support so I'll try to use that for now, just wanted to add some context 👍
