### ISSUE TITLE
Crash when loading second workspace

### ISSUE THREAD

**Issue by dvic** [elixir-tools/next-ls#336]
When I load a second workspace folder, the runtime gets shutdown without an error message.

Full reproduction with Helix instructions can be found here: https://github.com/dvic/nextls-bug-shutdown

It seems I can only reproduce it when I add the dependencies that are currently added to the `bar` project from the reproduction example. When I ran it without those set of dependencies, the project didn't crash. So it could be maybe a timing issue?

**Comment by mhanberg** [comment]
I tested this out, at least with helix 23.10 and the latest Next LS, can't reproduce anymore.

One thing to note is that Next LS will now ask you if you want it to run mix deps.get for you if your deps are outdated, but helix doesn't support the right LSP method for that yet, so you'll just need to make sure that your deps are up to date.
