### ISSUE TITLE
NextLS alternate binary path option?

### ISSUE THREAD

**Issue by tymoor** [elixir-tools/next-ls#352]
Trying to run NextLS via the elixir-tools.elixir-tools vscode extension with remote to ubuntu 22.04 WSL2.  Getting the following error on startup:

```
[NextLS] Using `elixir` found at: /mnt/c/Program Files/Elixir/bin/elixir
[NextLS] /mnt/c/Program Files/Elixir/bin/elixir: 247: exec: erl: Permission denied
[Error - 3:07:03 PM] [NextLS] Runtime for folder <project> failed to initialize
[Error - 3:07:03 PM] [NextLS] The runtime for <project> has crashed with reason: {:shutdown, :portdown}
```
My WSL instance has elixir installed via asdf with shims at:
```
<user>@<machine>:~/apps/<project_dir>$ which elixir
/home/<user>/.asdf/shims/elixir
```
Is there a way to tell NextLS to use that executable directory?  For example, the pantajoe.vscode-elixir-credo extension lets you define an executable directory:

**Elixir > Credo: Execute Path**
Specifies the execute path where mix can be run from, e.g., /usr/bin/.asdf/shims
`"elixir.credo.executePath": "/home/<user>/.asdf/shims"`

**Comment by mhanberg** [comment]
Are you able to launch VScode from the WSL terminal? It's not inheriting your path so the only elixir it finds is in windows. 

The elixir it's trying to use is to start the runtime,which should be your projects version.

**Comment by tymoor** [comment]
Thanks - that must have been what I did differently.  Appreciate the help!
