### ISSUE TITLE
Completions error when triggered outside of a module

### ISSUE THREAD

**Issue by mhanberg** [elixir-tools/next-ls#406]
## Description

When typing outside of a module, completions are not showing up.

I believe that this is due to calculating the module name to include in the defmodule snippet.

**Comment by mhanberg** [comment]
cc @lucacervello

**Comment by lucacervello** [comment]
I can't reproduce, It works just fine for me.

**Comment by mhanberg** [comment]
Weird, I'll try again

**Comment by mhanberg** [comment]
![CleanShot 2024-04-02 at 23 33 34@2x](https://github.com/elixir-tools/next-ls/assets/5523984/18c14f32-487b-4f82-820a-5b222ccd96e9)

ahh, so its unrelated to the snippet, and I think I introduced it in the last commit that is on main.

It seems to get mad if you cursor is in the column 1 or 2 (1 based column)

i'll fix it
