### ISSUE TITLE
Suggestions not working in Zed

### ISSUE THREAD

**Issue by andreicek** [elixir-tools/next-ls#407]
I added the following to the editor config:

```json
  "elixir": {
    "lsp": "next_ls"
  },
```

and observing the server logs after a while i get:

```
[NextLS] Compiled !
```

Code navigation works, but when I start typing nothing pops up. Looking at RPC messages I see a bunch of:

```
// Send:
{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":
```

Which looks fine? Any help debugging this?

Editor version: Zed Preview 0.130.0

```
[NextLS] NextLS v0.15.0 has initialized!
[NextLS] [extension] Credo initializing with options %NextLS.InitOpts.Extensions.Credo{enable: true, cli_options: []}
[NextLS] Booting runtimes...
[NextLS] Beginning DB migration...
[NextLS] Database is being upgraded from version 0 to 5.
```

**Comment by mhanberg** [comment]
You have to enable them, as they are currently experimental. 

I believe this is the correct settings, I'll double check when I get back to a computer. 

```json
"lsp": {
  "next_ls": {
    "initialization_options": {
      "experimental": {
        "completions": {"enable": true}
      }
    }
  }
}

```

Also, your Next LS version is very old, I think if you delete it from wherever Zed installs it, it will download the latest version where you restart zed.

**Comment by mhanberg** [comment]
Those settings don't seem to work, but I swear I had tested them before and seen it working.

I've reached out to Zed to see what's going on.

**Comment by mhanberg** [comment]
Might be related: https://github.com/zed-industries/zed/issues/7636

**Comment by mhanberg** [comment]
Got it figured out, the name is "next-ls" when under the lsp object

![CleanShot 2024-04-04 at 14 16 33@2x](https://github.com/elixir-tools/next-ls/assets/5523984/d0980161-a2ab-4c6b-b22c-f9f4ac9f8459)

```json
{
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "vim_mode": true,
  "elixir": {
    "lsp": "next_ls"
  },
  "lsp": {
    "next-ls": {
      "initialization_options": {
        "extensions": {
          // example configuring the extensions
          "credo": { "enable": false }
        },
        "experimental": {
           // example configuring the experimental options
          "completions": { "enable": true }
        }
      }
    }
  }
}
```

**Comment by mhanberg** [comment]
I updated the docs
