### ISSUE TITLE
Nix flake doesn't seem to work

### ISSUE THREAD

**Issue by lytedev** [elixir-tools/next-ls#412]
```
$ uname -a
Linux foxtrot 6.8.1 #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar 15 18:19:29 UTC 2024 x86_64 GNU/Linux
$ nix run github:elixir-tools/next-ls#default --accept-flake-config
error: FileNotFound
```

Let me know if I can provide anything else!

**Comment by lytedev** [comment]
After more tinkering, it looks like this is only relevant when using the Cachix cache. I edited the original message for clarity, adding `--accept-flake-config`.

**Comment by lytedev** [comment]
The "ci" package in the Flake also seems to fail, though that may be purposeful:

```
$ nix run github:elixir-tools/next-ls#ci --no-substitute
```

I'm diving deeper into this. It looks like there is some possible correlation between whatever Cachix is giving me versus me actually building it from the Flake myself. I found this issue, which is possible part of the problem on my end. Experimenting now. https://github.com/NixOS/nix/issues/6830

**Comment by mhanberg** [comment]
I think i can delete the ci package, i created it when i was going to use it for CI and then i never ended up using it

**Comment by lytedev** [comment]
I am trying to "reset" my Nix cache with some combination of these:

```
# make sure I'm not _using_ NextLS actively by closing editors that may be holding onto it or "pulling it into my Nix profile"
$ sudo rm -r ~/.nix/cache
$ sudo nix-collect-garbage -d
$ nix-collect-garbage -d
```

But still have one machine where `nix run` has the error and another one that does not.

**Comment by mhanberg** [comment]
I think i fixed this my adjusting how CI runs cachix and by clearing the cache and uploading existing latest release to the cache.

Please re-open if it continues to be a problem
