### ISSUE TITLE
Unnecessary (?) completions on "do|"

### ISSUE THREAD

**Issue by teamon** [elixir-tools/next-ls#470]
<img width="264" alt="image" src="https://github.com/elixir-tools/next-ls/assets/8083/679899ba-f93b-468e-961e-fe5dc2f0d887">

It seems that ` do|` triggers completions and when hitting enter it will insert `defoverridable` instead of going to the next line. Since `do` is a keyword I think it should skip completions (ideally go to the next line and insert `end` if needed)

**Comment by mhanberg** [comment]
You hit `d` with triggers the completions, then then the editor fuzzy filters them down to show what's in the screenshot. 

Is this zed? I'm not sure why it would auto select the first option, I imagine that has other consequences. 

Orthogonally, can probably add `do` as a completion candidate.

**Comment by teamon** [comment]
This one is from vscode.
ElixirLS seems to prioritize do as a reserved keyword and selects it as the first option.

Can I can test something else or get some logs to see why this happens?

**Comment by mhanberg** [comment]
To clarify, what are you wanting to test? Why VScode is selecting the completion item?

**Comment by teamon** [comment]
Well just anything I can do to help :)

**Comment by mhanberg** [comment]
Gotcha, well I'll clarify:

- `do` is not a completion item in Next LS, so it not appearing is expected (this can be changed if desired), nothing to debug. 

- VScode auto selecting the first candidate is not in my control, there might be settings around it, but I don't use it so I'm unaware.

**Comment by mhanberg** [comment]
![image](https://github.com/elixir-tools/next-ls/assets/5523984/0ff72286-2731-47ce-a616-2882544ebf7f)

Changing the second option is probably what you want.

**Comment by teamon** [comment]
I've checked with Zed and there completions are shown on `d`, then hidden on `do` and then shown again on `do<any other character>`.

Thanks for all the help, I'm going to close this for now.
