### ISSUE TITLE
code actions

### ISSUE THREAD

**Issue by mhanberg** [elixir-tools/next-ls#49]
Tracking ticket, please comment with ideas for code actions!

- [x] mark unused variable with underscore
- [x] alias module
- [x] require module (like Logger)
- [ ] extract variable
- [ ] extract function
- [ ] inline function
- [ ] inline variable

**Comment by biletskyy** [comment]
we also could convert 'if' to/from inline version

**Comment by mpmiszczyk** [comment]
convert function call to pipe, convert pipe to function call

**Comment by sesamzoo** [comment]
Hi @mhanberg,

I guess, you can update the status of the following tasks

> * [ ]  mark unused variable with underscore

-- https://github.com/elixir-tools/next-ls/blob/v0.19.2/test/next_ls/extensions/elixir_extension/code_action/unused_variable_test.exs

> * [ ]  require module (like Logger)

-- https://github.com/elixir-tools/next-ls/blob/v0.19.2/test/next_ls/extensions/elixir_extension/code_action/require_test.exs

**Comment by NJichev** [comment]
Closing in favour of #434, #435, #438, #439
