### ISSUE TITLE
Elixir LS version outdated?

### ISSUE THREAD

**Issue by mxgrn** [elixir-tools/next-ls#520]
I have to admin I still don't fully understand how Next LS is using Elixir LS, but when I'm getting the prompt:

```
Install ElixirLS                                                                                                                                                         
1: Yes                                                                                                                                                                   
2: No                                                                                                                                                                    
Type number and <Enter> or click with the mouse (q or empty cancels):
```

... and I choose 1 (I should, right?), I'm getting:

```
Cloning ref tags/v0.19.0 from repo elixir-lsp/elixir-ls
```

However, I'm seeing that Elixir LS is currently 0.21. Can this be an issue?

**Comment by mhanberg** [comment]
The default version is hardcoded, just needs to be bumped.

**Comment by mhanberg** [comment]
Oh, this is also an elixir-tools.nvim issue, not Next LS. 

Elixir LS is enabled by default, so you must disable it if you don't want to use it.

**Comment by mxgrn** [comment]
> Elixir LS is enabled by default, so you must disable it if you don't want to use it.

Any pointer to where I can read what Elixir LS adds? I thought Next LS is supposed to _replace_ it. Didn't expect them to me complementary.

**Comment by mxgrn** [comment]
https://github.com/elixir-tools/elixir-tools.nvim/issues/215
