### ISSUE TITLE
prompt to run mix deps.get

### ISSUE THREAD

**Issue by mhanberg** [elixir-tools/next-ls#53]
if you don't have dependencies installed, the editor should prompt you to install them and accept a yes or no. 

this should avoid having to leave the editor, run `mix deps.get`, and open it again.

**Comment by mhanberg** [comment]
@camilleryr this would be a really helpful one to tackle if you want to try it.

The gist is, when we detect a compiler error related to deps, we make a (window/showMessageRequest)[https://hexdocs.pm/gen_lsp/0.6.0/GenLSP.Requests.WindowShowMessageRequest.html] request from the server to the client to ask for a "yes/no"

I am opting to make this a prompt, because ElixirLS seemed to have many issues with auto running mix deps.get, so i'd like to try something different.

I'm not sure exactly how we should detect that deps have changed, but you'd have to figure that part out 😉.

let me know what you think!

**Comment by camilleryr** [comment]
@mhanberg - That sounds great! I was actually looking into this earlier, Ill see what I can cook up with for detecting if the deps have changed and let you know what I come up with!

**Comment by mhanberg** [comment]
awesome! thank you!

**Comment by mhanberg** [comment]
@camilleryr any updates?
