### ISSUE TITLE
Should not execute config/runtime.exs

### ISSUE THREAD

**Issue by mhanberg** [elixir-tools/next-ls#97]
## Description

This was noticed by a user who used a dependency in their config/runtime.exs file, which was not loaded yet because their app was not compiled at all.

But, they also showed that by using functions like `System.fetch_env!/1`, the config will fail and the app will fail to start.

## Solution

Need to find a way to start the runtime without it executing any of the Application config files.

**Comment by mhanberg** [comment]
I think a workaround for you right now would be to wrap your entire runtime.exs file in `if not System.get_env("NEXT_LS_PARENT_PID") do`

this env var is set by Next LS, so if it is present, it means you are in Next LS and can avoid executing anything

**Comment by mhanberg** [comment]
I published 0.5.2 that sets an `LSP` variable, so you can do `if System.get_env("LSP") do`

**Comment by lud-wj** [comment]
Using `NEXT_LS_PARENT_PID` works with a custom run with TCP but it does not work with the default stdio adapter (and letting the extension start it itself)

```
[Error - 13:06:35] Client NextLS: connection to server is erroring. Shutting down server.
[Error - 13:06:35] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
```

I'm using vscode and the last extension version is one week old so I did not try with the "LSP" variable.


Besides, when I start the tool from a shell ( `NEXTLS_VERSION=0.5.1 /home/lud/.vscode/extensions/elixir-tools.elixir-tools-0.2.2/bin/nextls --port 9999` ) the vscode output shows that the app is compiling, an I can have the current file symbols, but there is no code formatting and the workspace symbols do not work, they always display the symbols for the same module. Not sure if it is expected or related to the runtime.exs problem though.

**Comment by mhanberg** [comment]
The extension version is not tied to the NextLS version. When you start it normally it will fetch the latest version of NextLS. 

With regard to your last statement, did you let it finish compiling? Or were those features not working while it was compiling?

**Comment by mhanberg** [comment]
Can you remind me what your exact elixir and OTP versions are?

**Comment by lud-wj** [comment]
IIRC the compilation was long time finished. I'm leaving the office for now but I can run any tests you want later.

```
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.14.0 (compiled with Erlang/OTP 25)
```

**Comment by mhanberg** [comment]
@lud-wj 

Let me know if you get to try this out again and if it fixed your issues.

**Comment by lud-wj** [comment]
Hello, I see a vscode version from 4 days ago. Same errors on my side, telling that the server cannot be started

It works though, if I run the server manually and connect with TCP with this version of the extension:

```
NEXTLS_VERSION=0.5.4 /home/lud/.vscode/extensions/elixir-tools.elixir-tools-0.3.0/bin/nextls --port 9999
```

**Comment by mhanberg** [comment]
The vscode extension version is not tied to the next ls version. It always fetches the latest version of next ls automatically. 

But, you now can set the version from the extension. Could you try that just to be sure?

**Comment by lud-wj** [comment]
I can confirm that it works now with this configuration:

```json
  "elixir-tools.credo.enable": false,
  "elixir-tools.nextls.enable": true,
  "elixir-tools.nextls.version": "0.5.4",
```

**Comment by mhanberg** [comment]
Delete the .elixir-tools folder so it forces it to rebuild the lookup table.

**Comment by mhanberg** [comment]
Make sure they aren't anything in these cases that haven't been implemented yet: https://www.elixir-tools.dev/next-ls/#definition

**Comment by lud-wj** [comment]
Ah yes, that should be it. Thank you.
